input_polygons:
  - datasets: 
      - ./data/shp/justSM2.shp
    uniqueid: nid
    lifting: Building
    height_field: relativeh

lifting_options: 
  Building:
    lod: 1
    floor: true
    inner_walls: true
    triangulate: false
    ground:
      height: percentile-10
      use_LAS_classes:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7

input_elevation:
  - datasets:
    - ./data/lidar/output-50cm_2997013d4_v1.2.las
#      - /home/nate/projects/sm3d/data/lidar/output-50cm_2997013d4.las
#   omit_LAS_classes:
#     - 1 # Unclassified
#     - 2 # Ground
#     - 3 # Low vegetation
#     - 4 # Medium vegetation
#     - 5 # High vegetation
#     - 7 # Noise
#     - 13 # Wire guard
#     - 14 # Wire conductor
    thinning: 0

options:
  building_radius_vertex_elevation: 8.0
  radius_vertex_elevation: 6.0
  threshold_jump_edges: 0.5
